# permissions for end users to view visitors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: visitor-viewer-role
rules:
- apiGroups:
  - my.domain
  resources:
  - visitors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - my.domain
  resources:
  - visitors/status
  verbs:
  - get
