# permissions for end users to edit visitors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: visitor-editor-role
rules:
- apiGroups:
  - my.domain
  resources:
  - visitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - my.domain
  resources:
  - visitors/status
  verbs:
  - get
