apiVersion: apps/v1
kind: Deployment
metadata:
  name: bugzilla
spec:
  replicas: 1
  selector:
    matchLabels:
        app: bugzilla-pod
  template:
    metadata:
      labels:
        app: bugzilla-pod
    spec:
      containers:
      - name: bugzilla-pod
        image: bugzilla/bugzilla-dev
