apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume-nfs
  labels:
    type: nfs
spec:
  storageClassName: nfs
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.173.160.42
    path: "/aseqa_archive3"
