apiVersion: v1
kind: Service
metadata:
  labels:
    system: secondary
  name: service-nginx
  namespace: default
spec:
  ports:
  - nodePort: 31550
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    system: secondary
  sessionAffinity: None
  type: NodePort
